### ISSUE TITLE
suggestion: include announce per month/year

### ISSUE THREAD

**Issue by comonier** [Twi5TeD/PlayTime#33]
**I would like to pay salary to my staffs, but for that I would need to know if they reached the working hours account per month**
   So my idea is to know if it is possible to create a type of verification for the server owner to know if his employees are really working:
   
example:

/playtime check player april
```diff
- line1: you can't check a month that hasn't arrived yet this year, it's february
```
/playtime check player
```yaml
line1: player played 56 hours this month
line2: player played 136 hours last month, January.
line3: player played a total of 192 hours on this year 2023
line4: player played a total of 2536 hours in 2022.
line5: type: /playtime check player 2022 to list player played time in 2022.
```

/playtime check player 2022
```yaml
line1: player played 211,33 in January
line2: player played 211,33 in February 
line3: player played 211,33 in March 
line4: player played 211,33 in April 
line5: player played 211,33 in May 
line6: player played 211,33 in June 
line7: player played 211,33 in July 
line8: player played 211,33 in August 
line9: player played 211,33 in September 
line10: player played 211,33 in October 
line11: player played 211,33 in November 
line12: player played 211,33 in December
```
