### ISSUE TITLE
Issue with /playtime top

### ISSUE THREAD

**Issue by Smudgge** [Twi5TeD/PlayTime#40]
```yaml
Server Version: 1.19.4
Plugin Version: 3.6
```

When executing `/playtime top` there is no data. Yet there is data.
![Screenshot 2023-06-21 at 6 30 54 pm](https://github.com/Twi5TeD/PlayTime/assets/68658429/baec6578-0293-48b2-8d4c-8e51d51f26fb)
![Screenshot 2023-06-21 at 6 32 39 pm](https://github.com/Twi5TeD/PlayTime/assets/68658429/71818a2f-36bc-4dd1-ac68-f089ed41c08c)

# Config
```yaml

placeholder:
  top:
    name: none
    time: '-'
time:
  second:
    enabled: true
    prefix: s
  minute:
    enabled: true
    prefix: m
  hour:
    enabled: true
    prefix: h
  day:
    enabled: true
    prefix: d
  week:
    enabled: false
    prefix: w
messages:
  no_permission:
  - '&4[&6Playtime&4] &cYou do not have permission.'
  doesnt_exist:
  - '&4[&6Playtime&4] &cPlayer %offlineplayer% has not joined before!'
  player:
  - '&4[&6Playtime&4]'
  - '&6%playtime_player%''s stats'
  - '&6PlayTime: &a%playtime_time%'
  - '&6Times Joined: &a%playtime_timesjoined%'
  offline_players:
  - '&4[&6Playtime&4]'
  - '&6%offlineplayer%''s stats'
  - '&6PlayTime: &a%offlinetime%'
  - '&6Times Joined: &a%offlinetimesjoined%'
  other_players:
  - '&4[&6Playtime&4]'
  - '&6%playtime_player%''s stats'
  - '&6PlayTime: &a%playtime_time%'
  - '&6Times Joined: &a%playtime_timesjoined%'
  playtimetop:
    header:
    - '&bTop &e10 &bplayers playtime:'
    - ''
    message:
    - '&a%position%. &b%player%: &e%playtime%'
    footer:
    - ''
  server_uptime:
  - '&4[&6Playtime&4] &6Server''s total uptime is &a%playtime_serveruptime%'
  reload_config:
  - '&4[&6Playtime&4] &bYou have successfully reloaded the config.'
```
